user: hacky
group: hacky
pid: /home/hacky/hacky/tmp/pids/thin.pid
timeout: 30
wait: 30
log: /home/hacky/hacky/log/thin.log
max_conns: 1024
require: []
threaded: true
no-epoll: true
environment: production
max_persistent_conns: 512
servers: 1
daemonize: true
socket: /home/hacky/hacky/sockets/thin.sock